//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KardelenButik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayit
    {
        public int ID { get; set; }
        public string Isim { get; set; }
        public string Soyisim { get; set; }
        public string TelNo { get; set; }
        public Nullable<int> GunSayisi { get; set; }
        public Nullable<int> OdaNoID { get; set; }
        public Nullable<System.DateTime> GirisTarihi { get; set; }
        public Nullable<decimal> ToplamFiyat { get; set; }
    
        public virtual OdaNo OdaNo { get; set; }
    }
}
